# Generated by Django 4.0 on 2024-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_hotel_orderhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='expiry',
            field=models.DateTimeField(null=True, verbose_name='Expiry date'),
        ),
    ]
