# Generated by Django 4.0 on 2024-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tour_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='auth.User'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='place',
            field=models.CharField(max_length=50, verbose_name='auth.User'),
        ),
    ]
