# Generated by Django 4.0 on 2024-05-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_vendor_login_vendor_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor_Login',
        ),
        migrations.DeleteModel(
            name='Vendor_Signup',
        ),
    ]
