# Generated by Django 4.0 on 2024-05-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_vendor_login_delete_vendor_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendoruser', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
