# Generated by Django 4.0 on 2024-05-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_vendorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
