# Generated by Django 4.0 on 2024-05-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
