# Generated by Django 4.0 on 2024-06-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
