# Generated by Django 4.0 on 2024-06-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_customer_checkoutenquiry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutenquiry',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
