# Generated by Django 4.0 on 2024-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutenquiry',
            name='tourdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='checkoutenquiry',
            name='tourtravellers',
            field=models.IntegerField(null=True),
        ),
    ]
