# Generated by Django 4.0 on 2024-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_checkoutenquiry_tour_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutenquiry',
            name='tour_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='checkoutenquiry',
            name='tour_travellers',
            field=models.IntegerField(null=True),
        ),
    ]
