# Generated by Django 4.1.3 on 2024-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_checkoutenquiry_tour_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='expiry',
            field=models.DateField(null=True, verbose_name='Expiry date'),
        ),
    ]
