# Generated by Django 4.1.3 on 2024-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_tour_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutenquiry',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
